### PR TITLE
convert NM to pupa

### PR DESCRIPTION
**Pull request by cliftonmcintosh**
Related to #1442

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@jamesturk 

I have closed #1500 and opened this instead for converting NM to pupa.

**Comment by showerst** [comment]
Just a head's up that they've recently added two new status codes you'll have to handle to scrape bills. Here are the billy entries, you'll want to change the action coding.

 '7675': ('bill recalled from the House for further consideration by the Senate.', 'other'),

'7808': ('Law Without Signature', 'governor:signed'),

**Comment by cliftonmcintosh** [comment]
Thanks, @showerst 

I will make sure those new status codes are included.

**Comment by cliftonmcintosh** [comment]
This is still in progress. The conversion of bill and vote scraping is a lot more complicated than it was for legislators and committees. Since votes are no longer a part of bills but have references to bills, I intend to remove vote scraping from within the bill scraper and put it in its own scraper. I don't see a way to yield votes from within the bill scraper.

**Comment by cliftonmcintosh** [comment]
@jamesturk 

I think this is ready for review. I've run the scrapers and analyzed the mongo documents that are generated. They seem to be correct.

**Comment by cliftonmcintosh** [comment]
The scrapers that required the biggest changes were the bills and votes scrapers. Specifically, votes were previously being tallied as part of bill scraping. I moved vote collection into its own scraper.

Minor changes made in addition to the conversion:
- switching camelCase variables and method names to snake_case.
- using single-quoted strings consistently in files (because that was the most common form of string already in them)
- switching some old-style string building to the .format function for strings.

**Comment by jamesturk** [comment]
reviewing today

**Comment by cliftonmcintosh** [comment]
Thanks for the update!

**Pull request merged**
