### PR TITLE
[WIP] Convert WV to pupa!

### PR DESCRIPTION
**Pull request by erinspace**
- move old metadata to billy_metadata/wv.py
- new metadata in wv's __init__.py
- legislator scraper now in wv/people.py

### CODE REVIEW

**Comment by jamesturk** [comment]
@erinspace do you want to free this one up or do you think you'll get back to it?

**Comment by hiteshgarg14** [comment]
@jamesturk should I start working on it?

**Comment by jamesturk** [comment]
I believe @erinspace is hoping to take a second look at this one, might be
good to pick another (pupa-md branch needs love if you're looking for one)
 (Erin- let us know if you'd like to free this one up)

**Comment by jamesturk** [comment]
spoke w/ Erin and we're freeing this one up

**Comment by erinspace** [comment]
Thanks James!/Sorry for being delinquent =/

**Comment by jamesturk** [comment]
no worries 👍 closed in favor of #1748

**Pull request closed without merging**
