### PR TITLE
[WIP] Convert Iowa to Pupa

### PR DESCRIPTION
**Pull request by frenata**
- [x] metadata
- [x] legislators
- [ ] committees
- [x] bills
- [x] votes
- [x] events

### CODE REVIEW

**Comment by jamesturk** [comment]
@frenata just wanted to check if you had any more on this right now, no worries if not but just checking on status

**Comment by frenata** [comment]
Yeah I definitely intend to get back to work on this, just have needed to prioritize other tasks over the past few weeks.

**Comment by jamesturk** [comment]
I'm glad to take the committee portion on this week

**Comment by jamesturk** [comment]
merged, thanks!!!

**Comment by frenata** [comment]
Thanks, sorry for not getting back around to this sooner, the past few weeks have been super busy all of a sudden.

The committee stuff kept befuddling me when I looked back at it too, in terms of how to integrate the old style of committee membership added directly to legislators vs separate committee groups in pupa.

**Pull request closed without merging**
