### PR TITLE
[WIP] Colorado Pupa conversion

### PR DESCRIPTION
**Pull request by In-vincible**
#1442 
- [x] people 
- [x] #1612
- [x] bills
- [ ] actions
- [x] Events
- [x] committees
- [x] votes
dropping the pre 2016 bill,people off the list

### CODE REVIEW

**Comment by In-vincible** [comment]
#1612 issue will be fixed here.

**Comment by In-vincible** [comment]
Committee Scraper is running successfully. hence #1612 fixed, though I couldn't check for any difference in data saving of billy vs pupa.

**Comment by jamesturk** [comment]
OK to drop pre-2016 stuff

**Comment by In-vincible** [comment]
Lately have been really really busy, will conclude this one this weekend ;)

**Comment by jamesturk** [comment]
sorry for the very delayed review, wanted to check on the status of this one- is it ready to be reviewed (I'm glad to work on the merge conflict)

**Comment by In-vincible** [comment]
The actions part is still to be completed otherwise everything is saving, Sorry couldn't work till now, I will work on this one in next 2 days :) , in case you want to resolve it urgently you will need to just figure out the action file, and corresponding to that few commented lines in billy.py.

**Comment by jamesturk** [comment]
probably need to figure out what is going on w/ votes here, there are two vote scrapers :/

**Comment by jamesturk** [comment]
judging by the commits, I think we intended to abandon the old CO vote scraper, going to disable it (new vote scraper gets almost 2000 more votes!)

**Pull request merged**
