### PR TITLE
[WIP] Convert Louisiana to pupa

### PR DESCRIPTION
**Pull request by leslie-huang**
- [x] metadata
- [x] people
- [ ] bills
- [ ] committees
- [ ] events

### CODE REVIEW

**Comment by jamesturk** [comment]
noticed that legislators.py is gone, figure it was moved to people.py but not checked in

**Comment by leslie-huang** [comment]
Sorry, been a bit bogged down with some other projects and people.py is not quite done yet but will be soon!

**Comment by hiteshgarg14** [comment]
@leslie-huang : would you be interested in continuing with events, bills, etc.? If you're not available, I'd be happy to pick up where you left off. Thanks!

**Comment by leslie-huang** [comment]
Hi @hiteshgarg14 I'm finishing up a few other projects so it'll be another couple of weeks before I can get back to this. Sorry about the delay! If you all want to keep the pupa conversions moving, I totally understand if you want to take over!

**Comment by hiteshgarg14** [comment]
Hello, @leslie-huang! No issues and thank you for getting started. you can complete it as you get some free time. meanwhile, I will focus on other states.

**Comment by jamesturk** [comment]
thanks @leslie-huang - no worries about the timing, we're going to go ahead and wrap this one up in #1747  👍

**Pull request closed without merging**
