### PR TITLE
OK: Rename 1st special session, add 2nd spec sess, 2018

### LINKED ISSUE #2009: OK failing since at least 2017-12-10
OK has been failing since 2017-12-10

Based on automated runs it appears that OK has not run successfully in 2 days (2017-12-10).

```
  00:01:31 CRITICAL pupa: Session(s) 2017 First Special Session, 2017 Second Special Session were reported by Oklahoma.get_session_list() but were not found in Oklahoma.legislative_sessions or Oklahoma.ignored_scraped_sessions.
no pupa_settings on path, using defaults
ok (scrape, import)
  bills: {}
  people: {}
  committees: {}
```

Visit http://bobsled.openstates.org for more info.

### PR DESCRIPTION
**Pull request by estaub**
Fixes #2009.

### CODE REVIEW

**Comment by estaub** [comment]
**READY**.  There are bills for both new sessions; see http://webserver1.lsb.state.ok.us/WebApplication3/WebForm1.aspx 

Note: Oklahoma has gone from biennial to annual sessions.  The `name` (`2017-2018 Regular Session`) and `identifier` (`2017-2018`) on the **2017 regular session** are now misleading at best.  I can't guess the downstream risk of fixing them, so I left them alone.

**Comment by jamesturk** [comment]
This one we'll need to figure out what to do w/... since they've changed maybe we do need to break backwards compatibility but we'd want to do that in the database so we don't duplicate every bill

**Comment by mileswwatkins** [comment]
It doesn't look like Oklahoma has changed its pattern, actually. Confusing, though! The bill numbers are still continuous throughout the biennium, and 2018 contains all 2017 bills (just as 2016 contains all 2015 bills, etc).

For example, here're the bill lists for 2015 and 2016, showing continuation:

screen shot 2018-01-21 at 23 38 52
screen shot 2018-01-21 at 23 38 59

And here're the bill lists for 2017 and 2018, showing similar:

screen shot 2018-01-21 at 23 38 36
screen shot 2018-01-21 at 23 38 44

@estaub, I'm going to make a small edit to your PR here, to keep the biennium pattern, and merge it on in.

**Comment by mileswwatkins** [comment]
Ah, it doesn't look like you have [maintainer-commit](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) turned on @estaub; I'm going to spin my edits into a new, standalone PR.

**Comment by estaub** [comment]
@mileswwatkins Weird, I thought maintainer-commit defaults to on, and I never touch it.  I'll check next time.  This branch is ok to delete, right?

**Comment by mileswwatkins** [comment]
Maybe I misunderstood, you may be right @estaub :)

You can delete now, for sure.

**Pull request closed without merging**
