### PR TITLE
Convert GA to pupa

### PR DESCRIPTION
**Pull request by jmcarp**

### CODE REVIEW

**Comment by jmcarp** [comment]
Ready for review @hiteshgarg14 @jamesturk

**Comment by hiteshgarg14** [comment]
Bills:-
- `'_version_id': 2, '_internal_document_id': 164527,` fields are missing in new files. (differ on versions)
- `description`  is missing. (differ on description)
- difference in float value of `date`. 
- `differ on _guid 50296 != None`

People:-
- `differ on _guid 746 != None`
- Rest is good.

Committees:-
- Billy - `imported 93 committee files`, Pupa:- `imported 88 committee files`
-  ```
          committees some files only found in old
               upper_Economic Development and Tourism.json
               lower_Health & Human Services.json
               lower_Industry and Labor.json
               upper_Natural Resources and the Environment.json
               upper_Science and Technology.json
    ```
- Every file `differ on _guid 108 != None` and `differ on code Ret != None`
- Extra members in almost all committees.
- Every committee file `differ on description`.

Votes:-
- most of files `differ on chamber lower != upper`
- difference in float value of `date`. 

Should I attach the output file of compared scraped data?

**Comment by jmcarp** [comment]
Now that #1728 is merged, we're getting fields from `extras`, including `code`, `guid`, and `description`. I also fixed the missing committees and vote chambers. Could you give some examples of committees with extra members?

**Comment by hiteshgarg14** [comment]
```
lower_Juvenile Justice.json differ on members [{'name': 'Mandi Ballinger', '_guid': 808, 'role': 'Chairman'}, {'name': 'Regina Quick', '_guid': 829, 'role': 'Vice Chairman'}, {'name': 'Paulette Rakestraw', '_guid': 874, 'role': 'Secretary'}, {'name': 'Wes Cantrell', '_guid': 870, 'role': 'Member'}, {'name': 'Joyce Chandler', '_guid': 815, 'role': 'Member'}, {'name': 'J. Collins', '_guid': 4892, 'role': 'Member'}, {'name': 'Christian Coomer', '_guid': 756, 'role': 'Member'}, {'name': 'Clay Cox', '_guid': 87, 'role': 'Member'}, {'name': 'Pam Dickerson', '_guid': 771, 'role': 'Member'}, {'name': 'Chuck Efstration', '_guid': 846, 'role': 'Member'}, {'name': 'Stacey Evans', '_guid': 762, 'role': 'Member'}, {'name': 'Micah Gravley', '_guid': 821, 'role': 'Member'}, {'name': 'Scott Holcomb', '_guid': 769, 'role': 'Member'}, {'name': 'Wayne Howard', '_guid': 131, 'role': 'Member'}, {'name': 'Sheila Jones', '_guid': 143, 'role': 'Member'}, {'name': "Dar'shun Kendrick", '_guid': 770, 'role': 'Member'}, {'name': 'Jodi Lott', '_guid': 4879, 'role': 'Member'}, {'name': 'Mary Oliver', '_guid': 181, 'role': 'Member'}, {'name': 'Brad Raffensperger', '_guid': 875, 'role': 'Member'}, {'name': 'Dexter Sharper', '_guid': 831, 'role': 'Member'}, {'name': 'Jason Spencer', '_guid': 789, 'role': 'Member'}, {'name': 'Erica Thomas', '_guid': 868, 'role': 'Member'}, {'name': 'Keisha Waites', '_guid': 801, 'role': 'Member'}, {'name': 'Andrew Welch', '_guid': 777, 'role': 'Member'}, {'name': 'David Wilkerson', '_guid': 760, 'role': 'Member'}] != [{'name': 'Dewayne Hill', 'role': 'Member'}, {'name': 'John Meadows', 'role': 'Member'}, {'name': 'Dewey McClain', 'role': 'Member'}, {'name': 'Brian Strickland', 'role': 'Chairman'}, {'name': 'Bill Werkheiser', 'role': 'Member'}, {'name': 'Paulette Rakestraw', 'role': 'Secretary'}, {'name': 'Sheila Jones', 'role': 'Member'}, {'name': 'Sam Park', 'role': 'Member'}, {'name': 'Andrew Welch', 'role': 'Member'}, {'name': 'Keisha Waites', 'role': 'Member'}, {'name': 'Jodi Lott', 'role': 'Member'}, {'name': 'Pam Dickerson', 'role': 'Member'}, {'name': 'Todd Jones', 'role': 'Member'}, {'name': 'Terry England', 'role': 'Member'}, {'name': 'Brad Raffensperger', 'role': 'Member'}, {'name': 'Josh Bonner', 'role': 'Member'}, {'name': 'Joyce Chandler', 'role': 'Member'}, {'name': 'Clay Cox', 'role': 'Member'}, {'name': 'Jimmy Pruett', 'role': 'Member'}, {'name': 'Tom Kirby', 'role': 'Vice Chairman'}, {'name': 'Regina Quick', 'role': 'Vice Chairman'}, {'name': 'Wes Cantrell', 'role': 'Member'}, {'name': 'Barry Fleming', 'role': 'Member'}, {'name': 'Dexter Sharper', 'role': 'Member'}, {'name': 'Jason Shaw', 'role': 'Member'}, {'name': 'Chuck Efstration', 'role': 'Member'}, {'name': 'Micah Gravley', 'role': 'Member'}, {'name': 'Jason Spencer', 'role': 'Member'}, {'name': "Dar'shun Kendrick", 'role': 'Member'}, {'name': 'Scott Holcomb', 'role': 'Member'}, {'name': 'Christian Coomer', 'role': 'Member'}, {'name': 'Stacey Evans', 'role': 'Member'}, {'name': 'David Wilkerson', 'role': 'Member'}, {'name': 'Erica Thomas', 'role': 'Member'}, {'name': 'J. Collins', 'role': 'Member'}, {'name': 'Pedro Marin', 'role': 'Member'}, {'name': 'Mary Oliver', 'role': 'Member'}, {'name': 'Bruce Broadrick', 'role': 'Secretary'}, {'name': 'Wayne Howard', 'role': 'Member'}, {'name': 'Mandi Ballinger', 'role': 'Chairman'}]
```
```
lower_Legislative & Congressional Reapportionment.json differ on members [{'name': 'Johnnie Caldwell, Jr.', '_guid': 813, 'role': 'Chairman'}, {'name': 'Chuck Efstration', '_guid': 846, 'role': 'Vice Chairman'}, {'name': 'Susan Holmes', '_guid': 780, 'role': 'Secretary'}, {'name': 'Kimberly Alexander', '_guid': 806, 'role': 'Member'}, {'name': 'Sharon Beasley-Teague', '_guid': 63, 'role': 'Member'}, {'name': 'Kevin Cooke', '_guid': 757, 'role': 'Member'}, {'name': 'Pam Dickerson', '_guid': 771, 'role': 'Member'}, {'name': 'Matt Dollar', '_guid': 94, 'role': 'Member'}, {'name': 'Earl Ehrhart', '_guid': 97, 'role': 'Member'}, {'name': 'Rich Golick', '_guid': 112, 'role': 'Member'}, {'name': 'Mack Jackson', '_guid': 738, 'role': 'Member'}, {'name': 'Jan Jones', '_guid': 142, 'role': 'Member'}, {'name': 'Randy Nix', '_guid': 179, 'role': 'Member'}, {'name': 'Ed Rynders', '_guid': 198, 'role': 'Member'}, {'name': 'Sandra Scott', '_guid': 766, 'role': 'Member'}, {'name': 'Ed Setzler', '_guid': 203, 'role': 'Member'}, {'name': 'Lynn Smith', '_guid': 212, 'role': 'Member'}, {'name': 'Richard Smith', '_guid': 213, 'role': 'Member'}, {'name': 'Mickey Stephens', '_guid': 743, 'role': 'Member'}, {'name': 'Mable Thomas', '_guid': 224, 'role': 'Member'}] != [{'name': 'Karen Bennett', 'role': 'Member'}, {'name': 'J. Craig Gordon', 'role': 'Member'}, {'name': 'Scott Hilton', 'role': 'Member'}, {'name': 'Jimmy Pruett', 'role': 'Member'}, {'name': 'Sandra Scott', 'role': 'Member'}, {'name': 'Ed Setzler', 'role': 'Member'}, {'name': 'Katie Dempsey', 'role': 'Member'}, {'name': 'Chuck Efstration', 'role': 'Vice Chairman'}, {'name': 'Johnnie Caldwell, Jr.', 'role': 'Chairman'}, {'name': 'James Beverly', 'role': 'Member'}, {'name': 'Jodi Lott', 'role': 'Member'}, {'name': 'Wayne Howard', 'role': 'Member'}, {'name': 'Spencer Frye', 'role': 'Member'}, {'name': 'Trey Kelley', 'role': 'Member'}, {'name': 'Deborah Silcox', 'role': 'Member'}, {'name': 'Rich Golick', 'role': 'Member'}, {'name': 'Matt Hatchett', 'role': 'Member'}, {'name': 'Bruce Broadrick', 'role': 'Member'}, {'name': 'Don Parsons', 'role': 'Member'}, {'name': 'Matt Dollar', 'role': 'Member'}, {'name': 'Demetrius Douglas', 'role': 'Member'}, {'name': 'Sheila Jones', 'role': 'Member'}, {'name': 'Sharon Beasley-Teague', 'role': 'Member'}, {'name': 'Kimberly Alexander', 'role': 'Member'}, {'name': 'Allen Peake', 'role': 'Member'}, {'name': 'Jesse Petrea', 'role': 'Member'}, {'name': 'Sharon Cooper', 'role': 'Chairman'}, {'name': 'Buddy Harden', 'role': 'Member'}, {'name': 'Billy Mitchell', 'role': 'Member'}, {'name': 'Susan Holmes', 'role': 'Secretary'}, {'name': 'Karla Drenner', 'role': 'Member'}, {'name': 'Ed Rynders', 'role': 'Secretary'}, {'name': 'Betty Price', 'role': 'Member'}, {'name': 'Pam Stephenson', 'role': 'Member'}, {'name': 'Lee Hawkins', 'role': 'Vice Chairman'}, {'name': 'Michele Henson', 'role': 'Member'}, {'name': 'Mark Newton', 'role': 'Member'}, {'name': 'Howard Mosby', 'role': 'Member'}, {'name': 'Lynn Smith', 'role': 'Member'}, {'name': 'Kevin Cooke', 'role': 'Member'}, {'name': 'Mable Thomas', 'role': 'Member'}, {'name': 'Mickey Stephens', 'role': 'Member'}, {'name': 'Jan Jones', 'role': 'Member'}, {'name': 'Pam Dickerson', 'role': 'Member'}, {'name': 'Timothy Barr', 'role': 'Member'}, {'name': 'Karen Mathiak', 'role': 'Member'}, {'name': 'Mack Jackson', 'role': 'Member'}, {'name': 'Dexter Sharper', 'role': 'Member'}, {'name': 'Randy Nix', 'role': 'Member'}, {'name': 'Earl Ehrhart', 'role': 'Member'}, {'name': 'Mickey Stephens', 'role': 'Member'}, {'name': 'Richard Smith', 'role': 'Member'}, {'name': 'Rick Jasperse', 'role': 'Member'}, {'name': 'John Pezold', 'role': 'Member'}, {'name': 'Ed Rynders', 'role': 'Member'}]
```
Update:- Extra members not in almost all committees. Found these two examples. there may be other committees like this.

**Comment by jmcarp** [comment]
Hm, those look like the right memberships without the `guid` field. I did add `guid` to the `membership` objects to keep parity with the current code, but `pupa2billy` doesn't capture `extra` on that model--I didn't add it in #1728.

@jamesturk @mileswwatkins: is including `guid` on the `membership` actually useful? It could be used in matching names, but is it?

**Comment by jamesturk** [comment]
it isn't right now, probably fine like this.  I'll review this

**Pull request merged**
