### PR TITLE
MS: Add recent sessions, update legislators

### PR DESCRIPTION
**Pull request by rconnorlawson**
A small update to the MS scraper.

The first commit adds the metadata for the 20162E and 2017 sessions.

The second commit updates the party assignments for newly elected representatives. In Mississippi, candidates in special elections run without party labels, so all the representatives elected this November needed exceptions. "J. Walter Michel" was elected in a special election in March and now has an official party affiliation.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Thanks for the contribution, @rconnorlawson! It looks like @showerst merged in a similar one today, so I'm going to close this as a dup. But let the records show you beat him to the punch ;)

https://github.com/openstates/openstates/pull/1232

**Comment by showerst** [comment]
@rconnorlawson serves me right for not checking the outstanding PRs. I'll keep an eye on that in the future!

**Comment by rconnorlawson** [comment]
No problem, I'm glad the sessions got added.

I looked into the #1232, and it doesn't include the legislator party exceptions update. Without the changes in  4d1fa49, I was unable to scrape legislators on my machine. (It would quit on assertions every time) Do you still need this change?

**Comment by mileswwatkins** [comment]
There was a followup PR right after https://github.com/openstates/openstates/pull/1233

**Comment by rconnorlawson** [comment]
Got 'em. Thanks yall, keep up the good work!

**Pull request closed without merging**
