### PR TITLE
[WIP] MS "Mississippi" pupa

### PR DESCRIPTION
**Pull request by In-vincible**
#1442 
- [x] metadata
- [x] people 
- [x] committee
- [x] bills
- [x] votes

### CODE REVIEW

**Comment by In-vincible** [comment]
Not ready for review right now, few small glitches to consider.
1. replacing with char, gives type error, this to be fixed(though removing the replace works fine which is right now state).
2. To decide weather to avoid sponsor urls or save them, if save them where to save them(simple add_source to bill is also an option).

**Comment by In-vincible** [comment]
lint to be fixed.

**Comment by In-vincible** [comment]
@jamesturk ready for review.

**Comment by hiteshgarg14** [comment]
Compared the scraped data.

Votes & Bills differ on dates.
I think that it's correct:-  [ `_tz = pytz.timezone('CST6CDT')`]

Rest is good to go :+1:

**Pull request merged**
