### PR TITLE
Deal with missing NJ emails

### PR DESCRIPTION
**Pull request by samtregar**
It seems they've been removed from the Access DBs on the FTP site, but they still work and appear on many reps personal sites (although not in a form we could easily scrape).  The formula is simple enough - just AsmLAST@njleg.org and SenLAST@njleg.org.

### CODE REVIEW

**Comment by jamesturk** [comment]
I'm concerned about basing this on last name alone.  I know we made an exception before but it seems to me like if they've removed these we may want to let them go & possibly explore a manual solution in the future

**Comment by samtregar** [comment]
If they don't want to be emailed at these addresses, why are they still on their personal sites?  I suppose I could write a scraper that walks them, but of course they're all different so it would be more like a web crawler than the usual...

**Comment by samtregar** [comment]
Example of what I'm talking about: http://district10.senatenj.com/contact.php

**Comment by samtregar** [comment]
Actually now that I'm looking at it, these districtXX.senatenj.com sites do have a nice standard format and have both reps and sens emails.  If you won't take this patch I think I could do a scraper for them.  Let me know.

**Comment by jamesturk** [comment]
We should probably try to verify why they were removed, in other cases this has been b/c the emails have become a black hole, so serving them isn't useful anyway.

Either way, guessing the email addresses will inevitably lead us to giving people bad data.

**Comment by jamesturk** [comment]
I'll email a contact at the NJ Senate to try to find out more

**Comment by samtregar** [comment]
Do you have a contact?  I don't have any way to find out why they were removed.  Will you take a patch that scrapes their personal sites?

**Comment by samtregar** [comment]
Sounds good, thanks!

**Comment by samtregar** [comment]
Any progress on this?

**Comment by jamesturk** [comment]
just sent a second email and cc'd a Senator that had been in touch before

**Comment by jamesturk** [comment]
No response yet from any of the NJ emails... do we know anyone in NJ that is more likely to get a reply?  Hard to tell if the email is a black hole or they just don't want to talk to us

**Comment by samtregar** [comment]
I don't have any contacts personally.  I can try emailing a few at random to see if I can get a response though.

**Comment by samtregar** [comment]
Confirmed, at least one of these emails are live!  I just got a (hilariously late) reply from sensweeney@njleg.org.

**Comment by jamesturk** [comment]
ha alright, I guess we'll give them a try.  if you have a chance to fix this PR to work w/ the new NJ scraper that'd be great, otherwise I'll try to find some time in the next week or so

**Pull request merged**
