### PR TITLE
pupa IL scraper

### PR DESCRIPTION
**Pull request by fgregg**
I know that you don't want to pull this into master, but there does not seem to be an option for making a PR into a new branch. 

@jamesturk let me know how you want to track progress on this. do you want to see WIP PR, or just a big PR when I think it's done?

To do 
- [x] add committee memberships

### CODE REVIEW

**Comment by jamesturk** [comment]
This is good for now and I'll go ahead and create a pupa branch soon.

**Comment by fgregg** [comment]
I'm getting pretty close with this, but am currently blocked by https://github.com/opencivicdata/pupa/issues/274

**Comment by fgregg** [comment]
@jamesturk @mileswwatkins could you take a look at https://github.com/opencivicdata/pupa/issues/274

**Comment by fgregg** [comment]
Hello all, This PR now matches or exceeds the existing billy scraper in completeness. 

Votes are not resolved to the voter (but they weren't with billy either). I will add that resolution, but I thought I might give you all an opportunity to pull in what I have so far. 

I'd also like your thoughts on how to resolve the merge conflicts. Much of the original code has been supplanted by different approaches.

**Comment by fgregg** [comment]
@jamesturk, @mileswwatkins this is ready for review (or discussion about how to handle the merge conflicts if you want to wait till those are resolved)

**Comment by jamesturk** [comment]
👍  I wouldn't sweat the merge conflicts for now, I'll kick off a full run of this soon and we'll do a comparison between the old output & the new- if things look good there we can do the merge & throw out the old code

**Comment by jamesturk** [comment]
currently working from the https://github.com/openstates/openstates/tree/pupa-il branch

- [x] merged & resolved conflicts
- [x] by convention we have scrapers only grab the latest session if called without arguments, updated scrape() default behavior to do that
- [ ] people will need a similar update
- [ ] evaluate data & merge

**Comment by fgregg** [comment]
@jamesturk are you going to do the remaining items or do you want help?

**Comment by jamesturk** [comment]
I'll take a swing at it, I've been taking most of these over the finish
line as there are usually a few small tweaks we need at the end.  I'll let
you know if I can use any help, but it's looking pretty good so far :+1+

**Comment by fgregg** [comment]
:+1: :+1: :+1: :+1: :+1:

**Pull request merged**
