### PR TITLE
ME: Added support for deceased members #2154

### PR DESCRIPTION
**Pull request by sriks123**
Reolves issue #2154

### CODE REVIEW

**Comment by sriks123** [comment]
@jamesturk please review this PR.

**Comment by mileswwatkins** [comment]
It works, merging it in. Not super-happy that we have to special-case this in such a kluge-y way, but I noticed that the House does offer a spreadsheet with structured data, and that we could just scrape that; created a new, separate issue: https://github.com/openstates/openstates/issues/2158

**Comment by mileswwatkins** [comment]
By the way, @sriks123, next time you have a small PR that contains many commits, could you git-squash them down into a single one? Just to avoid having a messy Git history.

**Comment by sriks123** [comment]
Thanks for merging and yeah I will keep that in mind.

**Pull request merged**
