### PR TITLE
Convert CA to pupa

### PR DESCRIPTION
**Pull request by jmcarp**
* [x] people
* [x] committees
* [x] bills
* [x] events

### CODE REVIEW

**Comment by jmcarp** [comment]
This should be ready to test @jamesturk. I added a few things to the system and python requirements, so will need to rebuild the docker image to verify.

**Comment by jamesturk** [comment]
Notes after a quick review (I can take more time to look at these soon):

Bills:
- looks like bill actions aren't coming through
- we should preserve original sponsor type

People:
- multiple district offices are collapsed to one (this may be a pupa2billy issue)
- lots of these too
```
20172018_lower_75_Marie Waldron.json differ on district 75 != None
20172018_lower_75_Marie Waldron.json differ on party Republican != None
```

Votes:
-thresholds are dropped, should be set on extra
- it looks like in some cases no_count=0 became None

**Comment by jmcarp** [comment]
AFAICT Waldron is getting scraped correctly:

```
± ag waldron
membership_aeaf3bd6-35fd-11e7-bbe2-0242ac120005.json
1:{"end_date": "", "person_id": "aeaf33c0-35fd-11e7-bbe2-0242ac120005", "post_id": "~{\"label\": \"75\", \"organization__classification\": \"lower\", \"role\": \"member\"}", "role": "member", "links": [], "start_date": "", "organization_id": "~{\"classification\": \"lower\"}", "_id": "aeaf3bd6-35fd-11e7-bbe2-0242ac120005", "label": "", "person_name": "Marie Waldron", "extras": {}, "contact_details": [], "on_behalf_of_id": null}

membership_aeaf40ea-35fd-11e7-bbe2-0242ac120005.json
1:{"end_date": "", "person_id": "aeaf33c0-35fd-11e7-bbe2-0242ac120005", "post_id": null, "role": "member", "links": [], "start_date": "", "organization_id": "~{\"name\": \"Republican\", \"classification\": \"party\"}", "_id": "aeaf40ea-35fd-11e7-bbe2-0242ac120005", "label": "", "person_name": "Marie Waldron", "extras": {}, "contact_details": [], "on_behalf_of_id": null}

person_aeaf33c0-35fd-11e7-bbe2-0242ac120005.json
1:{"national_identity": "", "death_date": "", "identifiers": [], "other_names": [], "links": [{"url": "https://ad75.asmrc.org/", "note": ""}], "_id": "aeaf33c0-35fd-11e7-bbe2-0242ac120005", "name": "Marie Waldron", "gender": "", "birth_date": "", "extras": {}, "sources": [{"url": "http://assembly.ca.gov/assemblymembers", "note": ""}], "contact_details": [{"type": "address", "note": "District Office", "value": "P.O. Box 942849\nSacramento, CA 94249-0075"}, {"type": "voice", "note": "District Office", "value": "(916) 319-2075"}, {"type": "email", "note": "District Office", "value": "assemblymember.waldron@assembly.ca.gov"}, {"type": "address", "note": "District Office", "value": "350 West 5th Avenue, Suite 110\nEscondido, CA 92025"}, {"type": "voice", "note": "District Office", "value": "(760) 480-7570"}], "biography": "", "image": "http://assembly.ca.gov/sites/assembly.ca.gov/files/memberphotos/AD75-Marie_Waldron.jpg", "summary": ""}
```

I also see actions locally.

Sponsor type, thresholds and other counts should be fixed.

**Comment by jamesturk** [comment]
sorry for the eternal delay on this one.  I think when I said actions before I meant action types, going to pick up reviewing it ASAP though

**Comment by jamesturk** [comment]
at long last, this is merged 👍

**Pull request closed without merging**
