### PR TITLE
Pupa Conversion of CT

### PR DESCRIPTION
**Pull request by hiteshgarg14**
Related to #1442

-  [x] people.py
-  [x] events.py
-  [x] bills.py

### CODE REVIEW

**Comment by hiteshgarg14** [comment]
I am getting `import` error on `chardet`. Need help with this one.

**Comment by jamesturk** [comment]
can you try adding chardet to the requirements and rebuilding the docker
image?

**Comment by hiteshgarg14** [comment]
okay I am on it.

**Comment by hiteshgarg14** [comment]
File: events.py

`info['start'] = 2017-02-10T10:00:00Z`
`info['end']2017-02-10T12:15:00Z`

`start_time = self._tz.localize(when)` is working. but
`end_time = self._tz.localize(end)` is not working and giving error :- 
```
19:26:37 INFO billy: Save event 2016-12-08 15:45:00 committee:meeting: 
19:26:37 WARNING billy: Value u'2016-12-08T18:30:00+00:00' for field '<obj>.end' doesn't match any of 2 subtypes in [u'datetime', u'null']; errorlist = [FieldValidationError("Value u'2016-12-08T18:30:00+00:00' for field '<obj>.end' is not of type datetime",), FieldValidationError("Value u'2016-12-08T18:30:00+00:00' for field '<obj>.end' is not of type null",)]
19:26:38 INFO billy: billy-update abbr=ct
    actions=import,report
    types=bills,legislators,votes,committees,alldata,events
    sessions=2017
    terms=2017-2018
19:26:39 INFO billy: Finished importing 0 legislator files.
19:26:39 INFO billy: imported 0 vote files
19:26:39 INFO billy: imported 0 bill files
19:26:39 INFO billy: imported 0 committee files
Traceback (most recent call last):
  File "/opt/openstates/venv-billy//bin/billy-update", line 11, in <module>
    load_entry_point('billy', 'console_scripts', 'billy-update')()
  File "/opt/openstates/venv-billy/src/billy/billy/bin/update.py", line 413, in main
    import_report = _do_imports(abbrev, args)
  File "/opt/openstates/venv-billy/src/billy/billy/bin/update.py", line 159, in _do_imports
    report['events'] = import_events(abbrev, settings.BILLY_DATA_DIR)
  File "/opt/openstates/venv-billy/src/billy/billy/importers/events.py", line 37, in import_events
    data = prepare_obj(json.load(f))
  File "/opt/openstates/venv-billy/src/billy/billy/importers/utils.py", line 249, in prepare_obj
    convert_timestamps(obj)
  File "/opt/openstates/venv-billy/src/billy/billy/importers/utils.py", line 190, in convert_timestamps
    raise TypeError("expected float for %s, got %s" % (key, value))
TypeError: expected float for end, got 2016-10-05T19:00:00+00:00

```
and
`type(self._tz.localize(end)) == <class 'datetime.datetime'>`

**Comment by hiteshgarg14** [comment]
Pupa Conversion is complete. But There is one problem here....

File: events.py

`info['start'] = 2017-02-10T10:00:00Z`
`info['end'] = 2017-02-10T12:15:00Z`

`when = 2017-01-13 13:00:00`
`end = 2017-01-13 14:30:00`

`start_time = self._tz.localize(when)` is working. but
`end_time = self._tz.localize(end)` is not working and giving error :- 

```
19:26:37 INFO billy: Save event 2016-12-08 15:45:00 committee:meeting: 
19:26:37 WARNING billy: Value u'2016-12-08T18:30:00+00:00' for field '<obj>.end' doesn't match any of 2 subtypes in [u'datetime', u'null']; errorlist = [FieldValidationError("Value u'2016-12-08T18:30:00+00:00' for field '<obj>.end' is not of type datetime",), FieldValidationError("Value u'2016-12-08T18:30:00+00:00' for field '<obj>.end' is not of type null",)]
19:26:38 INFO billy: billy-update abbr=ct
    actions=import,report
    types=bills,legislators,votes,committees,alldata,events
    sessions=2017
    terms=2017-2018
19:26:39 INFO billy: Finished importing 0 legislator files.
19:26:39 INFO billy: imported 0 vote files
19:26:39 INFO billy: imported 0 bill files
19:26:39 INFO billy: imported 0 committee files
Traceback (most recent call last):
  File "/opt/openstates/venv-billy//bin/billy-update", line 11, in <module>
    load_entry_point('billy', 'console_scripts', 'billy-update')()
  File "/opt/openstates/venv-billy/src/billy/billy/bin/update.py", line 413, in main
    import_report = _do_imports(abbrev, args)
  File "/opt/openstates/venv-billy/src/billy/billy/bin/update.py", line 159, in _do_imports
    report['events'] = import_events(abbrev, settings.BILLY_DATA_DIR)
  File "/opt/openstates/venv-billy/src/billy/billy/importers/events.py", line 37, in import_events
    data = prepare_obj(json.load(f))
  File "/opt/openstates/venv-billy/src/billy/billy/importers/utils.py", line 249, in prepare_obj
    convert_timestamps(obj)
  File "/opt/openstates/venv-billy/src/billy/billy/importers/utils.py", line 190, in convert_timestamps
    raise TypeError("expected float for %s, got %s" % (key, value))
TypeError: expected float for end, got 2016-10-05T19:00:00+00:00

```
type(self._tz.localize(end)) == <class 'datetime.datetime'>

Although I removed `end_time` field for now.

**Pull request merged**
