### PR TITLE
Convert PA to pupa

### PR DESCRIPTION
**Pull request by jmcarp**
* [x] People
* [x] Bills
* [x] Committees
* [x] Events

### CODE REVIEW

**Comment by jmcarp** [comment]
Ready for review. Heads up: it looks like event scraping for PA hasn't worked for a while, so I rewrote it as part of this patch. I'm also using `python-dateutil`, because native python datetimes are bad :trollface:

**Comment by jamesturk** [comment]
haven't had a chance to debug why but right now it looks like votes aren't getting saved

**Comment by jmcarp** [comment]
I forgot a `yield from` 😓. We should be collecting votes now.

**Comment by jamesturk** [comment]
👍 checked and looked good.  For future reference: diff looked like more sources on bills, and a few action differences but all innocuous

**Pull request merged**
