### PR TITLE
people_email-lastname-issue.py #1784

### PR DESCRIPTION
**Pull request by PaulAnton**
Hi there, I am new to open source. I observed an issue explained by dnoble #1784
I edited the last_name variable by adding an additional if condition to make sure that the last_name variable doesn't take in suffix as last name. Please  review it and add it to main code if it makes sense :)

### CODE REVIEW

**Comment by jamesturk** [comment]
Thanks for this!  Would it be possible for you to fix the failing flake8 tests?

https://travis-ci.org/openstates/openstates/builds/243084303?utm_source=github_status&utm_medium=notification

Appreciate it!

**Comment by PaulAnton** [comment]
Sure, I will work on it!

**Comment by PaulAnton** [comment]
Can you have a look at it jamesturk? I have completed it and didn't get any flake8 error

**Comment by PaulAnton** [comment]
please*

**Comment by jamesturk** [comment]
hm, I'll take a look- still looks to be failing but I'll see what's going on when I get a chance

**Comment by PaulAnton** [comment]
Hi jamesturk, i understood the errors and corrected them

**Pull request merged**
