### PR TITLE
AR: Add 2018 fiscal session, and clean up session slug handling

### PR DESCRIPTION
**Pull request by mileswwatkins**
Currently waiting for any `2018F` bills to show up in this CSV: ftp://www.arkleg.state.ar.us/dfadooas/LegislativeMeasures.txt

The pre-files are up on the website, but not in their CSV yet. The session begins in mid-Feb, so should be soon.

Deprecates https://github.com/openstates/openstates/pull/2069

### CODE REVIEW

**Comment by mileswwatkins** [comment]
@jamesturk, looks like the regular-session slugs had been incorrectly migrated from Billy to Pupa, which had caused some confusion in the session management. I've corrected it; the odd-year "regular sessions" now have `R`s at the end of their IDs, as they shoud've all along, and had had in Billy metadata.

My question: will altering Pupa `__init__.py` session identifiers cause trouble for the data that's _already_ in the database? Like, cause a dup session to exist there? If so, what can we do about this?

**Comment by jamesturk** [comment]
yeah altering identifiers will require a lot of DB surgery, we'll need to look at options here and if this is necessary or can be avoided in any way, let's definitely hold this though

**Comment by mileswwatkins** [comment]
Yeah, let's discuss this at our weekly meeting on Monday.

**Comment by mileswwatkins** [comment]
screen shot 2018-02-08 at 23 08 36

**Comment by mileswwatkins** [comment]
@jamesturk, this one's ready for a second pair of eyes, but checked locally and working properly, so I'm 🎋 to merge.

**Pull request merged**
