### PR TITLE
Convert MO to pupa

### PR DESCRIPTION
**Pull request by jmcarp**
* [x] People
* [x] Committees
* [x] Bills
* [x] Votes

### CODE REVIEW

**Comment by jamesturk** [comment]
pushed one small change to https://github.com/openstates/openstates/tree/pupa-mo

- differences in bills/comms are OK
- legislators no differences
- votes have some issues right now, example:

('SB 108', 'On motion of Senator Romine, SCS for SB 108 was read the 3rd time and passed by the following vote:', 0) differ on yes_votes ['Brown', 'Chappelle-Nadal', 'Cunningham', 'Curls', 'Dixon', 'Eigel', 'Emery', 'Hegeman', 'Holsman', 'Hoskins', 'Hummel', 'Kehoe', 'Koenig', 'Kraus', 'Libla', 'Munzlinger', 'Nasheed', 'Onder', 'Richard', 'Riddle', 'Rizzo', 'Romine', 'Rowden', 'Sater', 'Schaaf', 'Schatz', 'Schupp', 'Sifton', 'Silvey', 'Wallingford', 'Walsh', 'Wasson', 'Wieland'] != ['Absent', 'Absent—Senators—None', 'Brown', 'Chappelle-Nadal', 'Cunningham', 'Curls', 'Dixon', 'Eigel', 'Emery', 'Hegeman', 'Holsman', 'Hoskins', 'Hummel', 'Kehoe', 'Koenig', 'Kraus', 'Libla', 'Munzlinger', 'NAYS—Senators—None', 'Nasheed', 'Onder', 'Richard', 'Riddle', 'Rizzo', 'Romine', 'Rowden', 'Sater', 'Schaaf', 'Schatz', 'Schupp', 'Sifton', 'Silvey', 'Wallingford', 'Walsh', 'Wasson', 'Wieland—33', 'leave—Senators—None', 'with']
('SB 108', 'On motion of Senator Romine, SCS for SB 108 was read the 3rd time and passed by the following vote:', 0) differ on passed True != False
('SB 108', 'On motion of Senator Romine, SCS for SB 108 was read the 3rd time and passed by the following vote:', 0) differ on yes_count 33 != 0

**Comment by jmcarp** [comment]
Looks like this was missing all vote counts because of an encoding issue. Should be fixed in the latest commit.

**Comment by jamesturk** [comment]
ah was just looking at the very same, thanks I'll run it now

**Comment by jamesturk** [comment]
merged, GH didn't autoclose b/c of the branch switches

**Pull request closed without merging**
