### PR TITLE
issue 1447: ID scraper fixed for new html files

### PR DESCRIPTION
**Pull request by jamesthechamp**
hey, 
this pr is for issue 1447
scraper for idoha commitee was based of old page does not exist. So i had pasted that is deprecated_committee.py and made a new scraper according to page:
https://legislature.idaho.gov/sessioninfo/2017/joint/
https://legislature.idaho.gov/committees/senatecommittees/
https://legislature.idaho.gov/committees/housecommittees/
i had added one field office_email with committee

### CODE REVIEW

**Comment by jamesturk** [comment]
thanks for this, would you be able to run flake8 on this & clean up the code a bit?  

also you can delete the old committees file if it isn't working

**Comment by jamesthechamp** [comment]
sure..

**Comment by jamesthechamp** [comment]
hey, 
i cleaned the code up a little please have a look at it.

**Comment by jamesturk** [comment]
hmm I think something happened with this branch, would it be possible to get a clean diff here?

**Comment by jamesturk** [comment]
also gave this a run and it looks like it is mangling legislator names:

example:

20:00:16 DEBUG billy: No matches for PhylisK.King                                        
20:00:16 DEBUG billy: No matches for MarkNye                                            
 20:00:16 DEBUG billy: No matches for MelissaWintrow                                     
 20:00:16 DEBUG billy: No matches for CliffordR.Bayer                                     
20:00:16 DEBUG billy: No matches for MathewW.Erpelding                                   
20:00:16 DEBUG billy: No matches for MarkHarris                                          
20:00:16 DEBUG billy: No matches for MaxineT.Bell                                        
20:00:16 DEBUG billy: No matches for MichelleStennett

**Comment by jamesthechamp** [comment]
hey,
Sorry 
I made a mess while cleaning up code i had send an another pr https://github.com/openstates/openstates/pull/1472 for this issue please have a look on it.

**Pull request closed without merging**
