### PR TITLE
Initial Texas vote refactor.

### PR DESCRIPTION
**Pull request by jmcarp**
As described in #1363, the Texas vote scraper currently uses regular expressions that are too specific to match many real votes. This is a first pass at a parser that's more accurate and IMO easier to read. I would love to get a second opinion on the approach before I continue with this.

### CODE REVIEW

**Comment by jamesturk** [comment]
Definitely like the property-based approach here, :+1:

Gave it a quick run locally and it looks better but didn't have a chance to
dive in to see how complete this is, let me know when you feel good w/ the
results and we'll merge.

**Comment by jmcarp** [comment]
I refactored voice votes and started on tests. I added an `is_amendment` flag for amendments, since parsing amendment bill ids could be error-prone (although probably doable)--does that make sense?

Anyway, I'm hoping somebody will have time to take a look at the output, but I'm fine with merging this afterwards. Parsing text like this is necessarily going to be flaky, but I think this is at least a decent foundation for later improvements, and it retrieves >0 votes 😄.

**Comment by jamesturk** [comment]
I got a chance to take a look at the output and the ones I spot checked look pretty good, one thing that seemed a bit off were the counts. 

Since the page doesn't seem to provide good counts it is fine to set the yes/no/other count to the len(yes_votes), etc.  We record them separately when they're listed separately so that we can verify that our counts match theirs (and also so that votes where individual voters are missing/etc. we still have the correct tally.

**Comment by jmcarp** [comment]
Got it, I'll use the lengths of the vote lists instead of the given counts. For my curiosity, could you link to an example of a vote where the counts in the text don't match the lists of yeas and nays?

**Comment by jamesturk** [comment]
One I was looking at was 

```
{
    "_type": "vote",
    "bill_chamber": "upper",
    "bill_id": "SCR 7",
    "chamber": "lower",
    "date": 1484110800.0,
    "is_amendment": false,
    "method": "record",
    "motion": "motion",
    "no_count": 1,
    "no_votes": [],
    "other_count": 1,
    "other_votes": [
        "Present",
        "not voting \u2014 Mr. Speaker(C)",
        "Dukes",
        "Martinez",
        "Stickland",
        "Swanson"
    ],
    "passed": true,
    "session": "85",
    "sources": [
        {
            "url": "http://www.journals.house.state.tx.us/HJRNL/85R/HTML/85RDAY02FINAL.HTM"
        }
    ],
    "state": "tx",
    "type": "other",
    "yes_count": 0,
    "yes_votes": [
        "Allen",
        "Alonzo",
        "Alvarado",
        "Anchia",
        "Anderson",
        "C.",
        "Anderson",
        "R.",
        "Ar\u00e9valo",
        "Ashby",
        "Bailes",
        "Bell",
        "Bernal",
        "Biedermann",
        "Blanco",
        "Bohac",
        "Bonnen",
        "D.",
        "Bonnen",
        "G.",
        "Burkett",
        "Burns",
        "Burrows",
        "Button",
        "Cain",
        "Canales",
        "Capriglione",
        "Clardy",
        "Coleman",
        "Collier",
        "Cook",
        "Cortez",
        "Cosper",
        "Craddick",
        "Cyrier",
        "Dale",
        "Darby",
        "Davis",
        "S.",
        "Davis",
        "Y.",
        "Dean",
        "Deshotel",
        "Dutton",
        "Elkins",
        "Faircloth",
        "Fallon",
        "Farrar",
        "Flynn",
        "Frank",
        "Frullo",
        "Geren",
        "Gervin-Hawkins",
        "Giddings",
        "Goldman",
        "Gonzales",
        "Gonz\u00e1lez",
        "Gooden",
        "Guerra",
        "Guillen",
        "Gutierrez",
        "Hefner",
        "Hernandez",
        "Herrero",
        "Hinojosa",
        "Holland",
        "Howard",
        "Huberty",
        "Hunter",
        "Isaac",
        "Israel",
        "Johnson",
        "E.",
        "Johnson",
        "J.",
        "Kacal",
        "Keough",
        "King",
        "K.",
        "King",
        "P.",
        "King",
        "T.",
        "Klick",
        "Koop",
        "Krause",
        "Kuempel",
        "Lambert",
        "Landgraf",
        "Lang",
        "Larson",
        "Laubenberg",
        "Leach",
        "Longoria",
        "Lozano",
        "Lucio",
        "Metcalf",
        "Meyer",
        "Miller",
        "Minjarez",
        "Moody",
        "Morrison",
        "Mu\u00f1oz",
        "Murphy",
        "Murr",
        "Neave",
        "Nev\u00e1rez",
        "Oliveira",
        "Oliverson",
        "Ortega",
        "Paddie",
        "Parker",
        "Paul",
        "Perez",
        "Phelan",
        "Phillips",
        "Pickett",
        "Price",
        "Raney",
        "Raymond",
        "Reynolds",
        "Rinaldi",
        "Roberts",
        "Rodriguez",
        "E.",
        "Rodriguez",
        "J.",
        "Romero",
        "Rose",
        "Sanford",
        "Schaefer",
        "Schofield",
        "Schubert",
        "Shaheen",
        "Sheffield",
        "Shine",
        "Simmons",
        "Smithee",
        "Springer",
        "Stephenson",
        "Stucky",
        "Thierry",
        "Thompson",
        "E.",
        "Thompson",
        "S.",
        "Tinderholt",
        "Turner",
        "Uresti",
        "VanDeaver",
        "Villalba",
        "Vo",
        "Walle",
        "White",
        "Wilson",
        "Workman",
        "Wray",
        "Wu",
        "Zedler",
        "Zerwas"
    ]
}
```

**Comment by jamesturk** [comment]
looks like the counts might always be 0 or 1? and also looking at that one it looks like there's an issue w/ legislators w/ initials specified

**Comment by jmcarp** [comment]
Neat, looks like some votes use "Yeas 27, Nays 5" and others use "27 Yeas, 5 Nays".

**Comment by jmcarp** [comment]
Updated. I wound up sticking with the given counts, since (1) many votes don't include lists of yea and nay voters, and (2) I noticed some typos in the voter lists that skewed the counts. Also, I'm thinking the bad counts either viva voca votes (which are categorized correctly now) or used the "Yeas 27" pattern instead of the "27 Yeas" pattern, both of which should be handled now.

**Comment by jamesturk** [comment]
Looks pretty good, turning TX vote scraping back on for the  next run

**Pull request merged**
