### PR TITLE
Parse NH committees from dynamic data.

### PR DESCRIPTION
**Pull request by jmcarp**
Starting on #1248.

* [x] Parse committees from http://gencourt.state.nh.us/dynamicdatafiles/
* [x] Parse committee membership from committee pages

Like @showerst said, it looks like we'll need to parse membership from committee pages. Will take a look at that this week.

### CODE REVIEW

**Comment by jmcarp** [comment]
Updated to parse committee memberships from committee pages. I noticed that the previous version of this parser only recognizes chair and member roles, but not vice chair--should we preserve that logic here?

**Comment by mileswwatkins** [comment]
@jmcarp, vice-chair and other committee positions are totally fair-game; scrape 'em!

**Comment by jmcarp** [comment]
This seems to be working as expected. Anybody have time to review?

**Comment by jamesturk** [comment]
checked it out locally and it looked good, thanks!

**Comment by jmcarp** [comment]
@jamesturk @mileswwatkins: if you all are in contact with NH, we could also ask them to add an association table between committees and legislators like in the legacy data to avoid some of the work added here.

**Comment by showerst** [comment]
I think i may have found a table with this data -- http://www.gencourt.state.nh.us/downloads/members.txt according to http://www.gencourt.state.nh.us/downloads/ it was updated Feb 7. Are there any members with more than 2 committee assignments?

**Comment by jmcarp** [comment]
@showerst: I looked at that table earlier, but didn't see committee roles (chair, vice chair, clerk).

**Comment by showerst** [comment]
@jmcarp ah, got it. So close!

**Pull request merged**
