### PR TITLE
Pupa mi

### PR DESCRIPTION
**Pull request by jmcarp**
* [x] people
* [x] committees
* [x] bills
* [x] events

### CODE REVIEW

**Comment by jmcarp** [comment]
@jamesturk: I didn't see an obvious pupa method corresponding to `Event.add_related_bill` in billy. I see that `EventAgendaItem` defines an `add_bill` method--do we need to add an agenda item to attach a related bill to an event?

**Comment by jamesturk** [comment]
hmm, yeah I think that'd be the only way right now, are you going to have to make an agenda item up to do this?

**Comment by jmcarp** [comment]
Updated to add related bills via agenda items.

**Comment by jamesturk** [comment]
starting (overdue) review of this one

**Pull request merged**
