### PR TITLE
Add tool to populate USB drives with Open States quickstart material

### PR DESCRIPTION
**Pull request by mileswwatkins**
I haven't gotten to run it on Linux or Windows (which might affect the paths or escaping), but the rest has been checked and confirmed working, as far as writing to the thumb drives.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Our 4 GB thumb drives are too small to contain all five of the services, so we'll jettison the `openstates/openstates.org` image. No biggie.

**Comment by mileswwatkins** [comment]
@jamesturk, this is now ready to go as far as I can tell, test it out on one of your thumb drives and let me know if I should tweak anything.

**Comment by mileswwatkins** [comment]
Pinging @showerst, to build a USB drive using this (on any environment), and then test whether that USB drive will be useful on a Windows machine!

**Comment by showerst** [comment]
@mileswwatkins got it, i'll give it a go tomorrow.

**Comment by jamesturk** [comment]
👍 I might be slow to get time to test this as next two nights I'm busy (unless snow disrupts), I'll definitely test by weds night though

**Pull request merged**
