### PR TITLE
OK: Update session metadata for 2018

### PR DESCRIPTION
**Pull request by mileswwatkins**
Continuing from https://github.com/openstates/openstates/pull/2012, maintains attribution for @estaub's commits.

@jamesturk, can you sanity-check this? Runs successfully for me locally, but I don't know for sure that it won't dup or confuse anything in the database. I _think_ we're good, though ;)

### CODE REVIEW

**Comment by jamesturk** [comment]
a bit confused by this, do the two sessions share bills/etc?

**Comment by mileswwatkins** [comment]
@jamesturk, yeah, OK does (and seems to have always) shared bill IDs and votes between sessions of a biennium. The 2017 bill list, for example, is the same as the 2018 bill list, but just frozen in time at the end of the 2017 calendar; that is, no updates to bill status/actions, no 2018-filed/-prefiled legislation. For example, see the bill list in my PR comment: https://github.com/openstates/openstates/pull/2012#issuecomment-359323717

**Comment by jamesturk** [comment]
OK, looking at the existing sessions list I understand now, we should add a comment to the legislative_sessions list to explain how this works since they effectively rename sessions

maybe something like:

# Sessions are named on OK's website as "{odd year} regular session" until the even year, when all data rolls over
# we have opted to name sessions {odd-even} Regular Session and treat them as such

# if adding a new odd-year session, add a new entry and copy the biennium pattern as above,
# if adding an odd-year session, all you'll need to do is update the scraped name

**Comment by mileswwatkins** [comment]
Ah, there's already a note, but I thought it was in __init__ rather than billy_metadata. I'll copy it over.

**Pull request merged**
