### PR TITLE
GA: Separate legislator names and districts in votes.

### LINKED ISSUE #1812: GA votes need name matching
The GA state senate is missing votes (e.g., [GAV00006507](https://openstates.org/ga/votes/GAV00006507/) doesn't have a single vote) **and** the state Assembly is missing votes (e.g., [GAV00006524](https://openstates.org/ga/votes/GAV00006524/) doesn't have a single vote). This appears quite widespread for the current term in GA, that votes seem to be missing on nearly every motion.

**Addendum.** The problem appears to be the clerks record votes as "LAST NAME, district number" which messes up the vote parsing. But if we simply remove the ", district number" part of the string, the votes are identified with the legislator correctly, which seems to fix the problem.

### PR DESCRIPTION
**Pull request by jmcarp**
[Fixes #1812]

### CODE REVIEW

**Comment by jmcarp** [comment]
Just noticed a similar fix in #1864. I see that @jamesturk was concerned about losing information about district, which I'm including here in the `note`; does that make sense? The Georgia API also includes legislator IDs along with votes, so we could expose those as well, but I don't see that pupa would make use of either the district number or the unique ID.

**Comment by jmcarp** [comment]
Would it be useful to add an optional district to the `vote` method for resolution by pupa?

**Comment by jamesturk** [comment]
i'm sort of torn on the right philosophy on these, on one hand- we could simply accept the strings as-is and then use the entity matching code to alias Jones-21st and Jones-4th to the proper Joneses.  The other approach is as you suggest, adding more custom code to support these cases.

The first is a more general solution, and better handles cases we've seen where they only provide the district disambiguator on one of the two (fun times), but I'm open to argument in favor of the latter over it

**Comment by jmcarp** [comment]
Could you point me to the entity matching code? I poked around pupa a bit, but I'm not sure where that logic lives, or what it does.

**Comment by jamesturk** [comment]
so the story in pupa is simply that if something is in other_names it can be resolved to the same entity- it is done here:

https://github.com/opencivicdata/pupa/blob/master/pupa/importers/base.py#L130
and 
https://github.com/opencivicdata/pupa/blob/master/pupa/importers/people.py#L37

billy had much more complex stuff going on, allowing manual resolution- which we're hoping to avoid as it became untenable, especially w/o dedicated intern resources

**Pull request merged**
