### PR TITLE
 MI: Some senator photo URLs not being scraped #2008 fixed

### PR DESCRIPTION
**Pull request by narendra36**

### CODE REVIEW

**Comment by narendra36** [comment]
I have made necessary changes that was told by @jamesturk in my previous pull request which I have closed. Please review this one @jamesturk @mileswwatkins

**Comment by mileswwatkins** [comment]
@narendra36, if your overall approach is to check whether these image resources exist, you could do something simpler that doesn't need to open a new webpage, like:

```
try:
    self.head('http://www.senate.michigan.gov/_images/' + surname + '.png')
    photo_url = 'http://www.senate.michigan.gov/_images/' + surname + '.png'
except scrapelib.HTTPError:
    try:
        self.head('http://www.senate.michigan.gov/_images/' + surname + '.jpg')
        photo_url = 'http://www.senate.michigan.gov/_images/' + surname + '.jpg'
    except scrapelib.HTTPError:
        photo_url = None
```

Does that make sense here, do you think? You've spent more time on this isuse, so I trust your call :)

**Comment by narendra36** [comment]
Yes! it does. I will implement it and  will update pull request. :)

**Comment by narendra36** [comment]
Hi, @mileswwatkins check it now. It works perfect. Thanks for review :)

**Comment by mileswwatkins** [comment]
Looking good. Let's call the name variable `surname` or `last_name` instead, since `firstname` is misleading. Then I'll merge it in!

**Comment by narendra36** [comment]
Ok I am updating.

**Comment by narendra36** [comment]
It's done. @mileswwatkins :)

**Pull request merged**
