### PR TITLE
Al 2017

### PR DESCRIPTION
**Pull request by showerst**
Updated Alabama code for website changes, and to add 2016 special and 2017 sessions.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
@showerst, does this contain all of the AL changes that you made? Or have there been more since (or in a different `showerst/openstates` branch)?

**Comment by showerst** [comment]
@mileswwatkins this is an older commit, but I don't see any updates on my fork, and I just ran it for 2017 and it seems to be completing fine, so should be good.

**Comment by mileswwatkins** [comment]
Gotcha, yeah, wanted to see if I could start reviewing this right away. Will do!

**Comment by mileswwatkins** [comment]
For me, this code seems to choke on the vacant seats in House Districts 58 and 67. Bills module looks solid, though! Can you add special-casing so that Legislator scraping works, then I'll review that output and merge this in?

**Pull request closed without merging**
